### ISSUE TITLE
Add Chart in the Market page

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-dashboard#105]

**Comment by Janaka-Steph** [comment]
Need to be more specific

**Comment by tiero** [comment]
> Need to be more specific

The sketch is flexible enough becacuse not clear what data we ca visualize:

- Trading Volume ( ie.  trade in + trade out) https://www.investopedia.com/terms/v/volumeoftrade.asp
- Fee Payouts

**Comment by tiero** [comment]
We should show the time windows of daily, weekly, monthly like uniswap https://info.uniswap.org/;#/
