### ISSUE TITLE
HealthCheck endpoint to gather info on the rpcproxy connection status

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-dashboard#118]

**Comment by tiero** [comment]
or maybe calling the daemon `isReady` shoudl be enought?

**Comment by Janaka-Steph** [comment]
I would say isReady is enough

**Comment by tiero** [comment]
`isReady` tells you the daemon works (and implicitly the proxy too) but we cannot really know if ONLY the proxy is down (and maybe we need to restart it?)

**Comment by Janaka-Steph** [comment]
In case it is useful https://github.com/grpc/grpc/blob/master/doc/health-checking.md
