### ISSUE TITLE
[Liquid RTK Query API] baseUrl should be dynamic

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#156]
liquid.api.ts
baseUrl depends on build time "network" config: `baseQuery: fetchBaseQuery({ baseUrl: network.explorerLiquidAPI })`

Change using this
https://stackoverflow.com/questions/69568818/how-to-dynamicly-chane-base-url-using-redux-toolkit

**Comment by tiero** [comment]
It should depends on the current state ie. Endpoints in Settings slice
