### ISSUE TITLE
Remove featured assets and fetch asset data

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#157]
At the moment we only have network to switch between "known assets" but those can be fetched via /asset endpoint and icon can be binded to ticker (for mainnet and testnet), regtest all generics is fine

**Comment by tiero** [comment]
We do like this already AFAIK, we only need to swtich the exploer API

**Comment by tiero** [comment]
We should at least have hardcoded L-BTC since they are not present on Blockstream asset registry for mainnet and testnet

<img width="444" alt="image" src="https://user-images.githubusercontent.com/3596602/150781416-1135a6fe-9c33-48a7-a09e-ef42185b64dd.png">
