### ISSUE TITLE
Password should be ascii

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#184]
`initwallet` should not take password as string but `Buffer.from(password, 'ascii')`.
Otherwise password will differ from one set from CLI.

**Comment by altafan** [comment]
The compiled js stub accepts the password as `Uint8Array | string` but it uses base64 conversion by default for the string case. This kind of "helper" can't be used because the password must be encoded in ascii format to be able to parse also special chars like `$`, `&`, etc.

**Comment by Janaka-Steph** [comment]
If I run this command `docker exec -it tdexd tdex init --seed "${mnemonic}" --password secret &>/dev/null`, then in the dashboard Unlock Wallet popup I type `secret`, password is invalid
