### ISSUE TITLE
Update to CRA 5 

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#186]
Blocker: https://github.com/DocSpring/craco-antd/issues/73
We need to use Craco or similar to have AntD to work with CRA because CRA doesn't support Less (open PR https://github.com/facebook/create-react-app/pull/10494).
Official DocSpring craco-antd is not maintained. 
This fork support CRA 5 https://github.com/kamronbatman/craco-antd.

We can use craco-less directly and configure it but Less variables in modifyVars have to be JSON so not maintainable and no hot reloading when modifying Less vars.

There is also this solution without Craco but there is an issue with CRA 5 https://github.com/tommie-lie/cra-antd-customization.

**Comment by rkhaslarov** [comment]
Could you please increase the priority of the feature?
