### ISSUE TITLE
Add script to create markets with assets of precision not 8

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#266]

**Comment by tiero** [comment]
But for regtest will not work since, nigiri-chopsticks does not know of the new precision?

**Comment by Janaka-Steph** [comment]
STEPH token has been created on testnet with precision 5 and hash b01e4d029b4f1fe487a865d8f04fdffe2bd335b0b7f8700092109e6f042f0609
