### ISSUE TITLE
Service unavailable always, even if correctly connected

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-dashboard#379]
https://www.loom.com/share/c4e12048e9164f9bb738bc62406f1708

**Comment by tiero** [comment]
commenting for now, not able to find quick solution

https://github.com/tdex-network/tdex-dashboard/pull/380/commits/7ee818f01b64340d052d1c68ee5086d1ec42edba

**Comment by Janaka-Steph** [comment]
We already have this effect just above the commented one:
```
  useEffect(() => {
    if (errorIsReady) {
      notification.error({
        message: 'Service is not available or credentials are wrong',
        key: 'service unavailable',
      });
    }
  }, [errorIsReady]);
```
It seems to me that the two effects are redundant.
