### ISSUE TITLE
Create Wallet & Restore Wallet: app fails to retrieve macaroon after creating a wallet via InitWallet

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-dashboard#382]
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/3596602/182432700-ae178e7a-f52a-42e3-bedb-a3ab0f6b0360.png">

# Full video

https://www.loom.com/share/08d323fd65e24522af55bd8bd8eb3d3e

The tdexdconnect URL is updated correctly after the InitWallet, but the dashboard fails

**Comment by tiero** [comment]
https://www.loom.com/share/425a438ba7f9492f8e1da5a690b81956

**Comment by Janaka-Steph** [comment]
I am not able to reproduce on regtest.

By the way, it seems the screenshot error "expected 1 macaroon" is a different error than the ones reported on Loom.
