### ISSUE TITLE
Make mandatory min height/widht

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-dashboard#398]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/3596602/184318478-23b69089-146a-4a26-a6c4-de346cdf34c3.png">

**Comment by Janaka-Steph** [comment]
I would forbid resizing below initial size (1180x800) because it's not just the font, the app design breaks in multiple places below that size.
https://tauri.app/v1/api/js/interfaces/window.windowoptions/#minheight
