### ISSUE TITLE
Tdex connect url validation

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#404]
Support TLS termination with CA signed certificate
See https://github.com/tdex-network/tdex-daemon/issues/622

- if cert is given and proto is not set, valid ✅ (we default to https in clients)
- if cert is given and proto is set to http, we return error ⛔️
- if cert is NOT given and proto is set to https we assume a CA signed certificate is setup
- if cert is NOT given and proto is set to http we assume insecure connection

**Comment by tiero** [comment]
Provider to test with https://tdexd.sevenlabs.ninja (password shared in DM)
