### ISSUE TITLE
Cannot connect to already initialized daemon

### ISSUE THREAD

**Issue by altafan** [tdex-network/tdex-dashboard#433]
I'm running the latest version of the daemon and dashboard.

My daemon is already initialized with a wallet, so when I start the dashboard, after I enter the connect URL the app redirects to Create or restore wallet view, while instead, I would expect it to show the modal to enter the password and unlock it.

Tested with @sekulicd, he managed to make it work after refreshing the page several times, while instead I'm not able to make it work correctly.

Demo: https://www.loom.com/share/acdeeed7666f47dc97f96d06e897561c

**Comment by tiero** [comment]
Is the operator authenticated with macaroon? If yes, You also need to pass the macaroon.

If not I guess we miss supporting this use-case, no-tls e no-macaroons

**Comment by Janaka-Steph** [comment]
@altafan @sekulicd When you have connection issues the first thing to do is to force reset via top right button

**Comment by tiero** [comment]
I am running the dashboard frontend in incognito mode and force reset as well.
https://www.loom.com/share/ec3e835b3e5b4ed3abc236c8a8cfc8b9

I think the problem here is that the daemon when started is locked, and the dashboard does not go lock in the `unlocked` status to determine if a) is `initialized` == true b) the Unlock modal should be shown when `unlocked` == false

**Comment by altafan** [comment]
> Is the operator authenticated with macaroon? If yes, You also need to pass the macaroon in the URL

I'm running the daemon in insecure mode locally and I'm sure the connect URL I'm using is the correct one `tdexdconnect://localhost:9000?proto=http`

**Comment by altafan** [comment]
@tiero I edited your last comment.. IsReady is the RPC you want to use to know the status of the daemon (the naming is really unfortunate :( ), while GetInfo returns info about the internal wallet such as root path, accounts etc.
