### ISSUE TITLE
Cannot pair with TLS daemon on Firefox

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#438]
Firefox use its own trusted certificate list instead of the operating system's keychain. So certificate should be added in Preferences > Privacy & Security > View Certificates.

However this is not enough. It seems that SS cert is rejected because it contains basicConstraints extension CA = true. Certificate should be generated without it.
See: https://stackoverflow.com/questions/59738140/why-is-firefox-not-trusting-my-self-signed-certificate

**Comment by tiero** [comment]
Thanks. Will investigate the `basicConstraints` generation, indeed should not be present in the cert generation is is only used as self signed cc/ @altafan
