### ISSUE TITLE
Convert amounts using CoinGecko

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#45]
https://www.sketch.com/s/cb01fe6f-bea1-4764-88e3-1eb98b23c708

**Comment by librepgp** [comment]
I've managed to setup the whole stack

tdex-dashboard
tdex-daemon
tdex-dconnect
nigiri

It's up and running now.

I have some questions about this feature:

- Is this for the "Fee Account Balance" to show up in USD/CAD value?
- The configuration for this should be located in the "settings" screen I imagine
- What other places should the fiat value appear?

**Comment by Janaka-Steph** [comment]
First you have to start with https://github.com/tdex-network/tdex-dashboard/issues/265, which will be used for this issue.

Then let's start replacing `0.00 USD` placeholders in Fee withdraw and Market withdraw pages. 

According to initial mockup we also display fiat values in Home page "Total earned" and "Fee Account Balance" _instead of_ current btc values. But for now we can only calculate fiat value for USDt since we don't have a price API for the other coins. So in "Total earned" and "Fee Account Balance" we can add fiat value below btc value but we can't replace it entirely.

**Comment by librepgp** [comment]
Understood, thank you.

I'll post the updates for this feature on the PR.
