### ISSUE TITLE
Show more does not work with "All" tx view selected

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-dashboard#456]
https://www.loom.com/share/3e53a67018844549afc9bed34e478b69

**Comment by Janaka-Steph** [comment]
I don't reproduce using testnet tdexdconnect://provider.tdex.network:19000. 
Can you share the node you used?

**Comment by tiero** [comment]
I used https://provider.tdex.network:9000 (you can retrieve URL using the username `tdex` and password you should know)
