### ISSUE TITLE
There is huge lag between startegy selection and button highlight

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-dashboard#457]
https://www.loom.com/share/f5589801180747a58dfca1da626b5a89

**Comment by Janaka-Steph** [comment]
Can you be more explicit?

**Comment by tiero** [comment]
At second 10 when switching from balanced to pluggable, it takes couple of seconds for the PLUGGABLE button to be highlighted with green border, although the toast "success" has been fired already
