### ISSUE TITLE
Mobile web version

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-dashboard#463]
### Pairing

The pairing screen should also have a QR code icon to open the camera to easy scan th connect URL (the daemon will support showing it https://github.com/tdex-network/tdex-daemon/issues/656)

### Dashboard Overview

Stack current objects vertically in a list view, in this order: 

  - Total Earned 
  - Markets 
  - Fee Account 
  
  ### Market Overview
  
- show Collected Swap Fees, Set Absolute Fee and Transactions only (hide Volume chart entirely
 
- keep top section navbar, market logos top-left and Withdraw, Deposit, Info, Wheel buttons top-right

**Comment by tiero** [comment]
As the first mobile version with minimal iteration on the layout, I would expose ready-only actions and components, hiding for now anything that requires user to input anything (change the fee, deposit, withdraw, create ner markets or edit market settings)

**Comment by Janaka-Steph** [comment]
The transaction table in market overview needs a full rework for small screens because it is not suitable.

**Comment by tiero** [comment]
What if we hide for now?

**Comment by Janaka-Steph** [comment]
> What if we hide for now?

It's already done, will push in a bit
