### ISSUE TITLE
Incorrect display of base and quote asset in dashboard

### ISSUE THREAD

**Issue by djkazic** [tdex-network/tdex-dashboard#504]
![telegram-cloud-photo-size-1-5145869226249137120-y](https://github.com/tdex-network/tdex-dashboard/assets/3331929/7e2247a5-87e2-41d3-98a8-daefa9f0ae75)
I was confused looking at my swap history, as it implied that all my trades were L-BTC in and FUSD out. However, there were actually two transactions that were FUSD in and L-BTC out.
![telegram-cloud-photo-size-1-5145869226249137122-y](https://github.com/tdex-network/tdex-dashboard/assets/3331929/f4acf16a-f176-4dbb-a005-3fdb0a950461)
```
tdex --version                                                                                                                                                                 [±master ●●]
tdex operator CLI version
Version: 0.9.1
Commit: b9044966c1f57eb1c25fe5d9da87c01443f206ca
Date: 2023-03-22T14:07:22Z
```

`0.1.56` tdex-dashboard

I did notice there's a dashboard update but I haven't installed it yet. Will update here if it fixes the issue.

**Comment by Janaka-Steph** [comment]
Thank you for opening that issue. It has been fixed on v1 branch, the next version that will be released very soon.
