### ISSUE TITLE
Reflection endpoint should be called via the proxy

### ISSUE THREAD

**Issue by altafan** [tdex-network/tdex-dashboard#506]
At the moment the dashboard calls the daemon's `/v1/info` endpoint via `fetch` but this can work only for daemons running in single-port mode.

In order to make the dashboard work correctly with daemons that run the operator and trade interfaces on different port, the right thing to do should be calling the endpoint via the embedded grpc proxy. This is because the operator interface does not come with REST endpoints like the trade one, so the calls must be done via grpc or grpc-web, ie. the embedded grpc-proxy.

**Comment by Janaka-Steph** [comment]
But the proxy is only available in Tauri as a Sidecar. How do we do for web?

Also I don't understand the problem. `/v1/info` is not on Operator interface, so why should we care?

**Comment by altafan** [comment]
The endpoint is registered on the operator interface, which doens't uses the gateway.

Can you make me recall how the web version of dashboard calls all other endpoints?

**Comment by Janaka-Steph** [comment]
I thought that `v1/info` comes from https://github.com/tdex-network/reflection. Are you sure it is on Operator?

Endpoints are called with GrpcWeb, not sure I get your question.

**Comment by djkazic** [comment]
It appears to be via operator interface. https://github.com/tdex-network/tdex-daemon/blob/a557c70d67627e28b148335c899037ac15ccbc88/api-spec/protobuf/tdex-daemon/v1/operator.proto#L13C3-L13C14

**Comment by Janaka-Steph** [comment]
@djkazic No this is something different. That's to get daemon's infos. But `v1/info` is Reflection

**Comment by djkazic** [comment]
Hmm. Any idea why that route returns 400 and an error about GRPC requiring HTTP2? I always get that no matter what.

**Comment by Janaka-Steph** [comment]
Do you call it with GrpcWeb?

**Comment by djkazic** [comment]
I'm not sure. I just hit F12 to open up the dev console on the dashboard when it was trying to onboard pair. The network requests tab showed the 400.

**Comment by tiero** [comment]
> 
> Endpoints are called with GrpcWeb, not sure I get your question.

Exactly the issue is solved if we use GrpWeb always with operator interface

**Comment by Janaka-Steph** [comment]
Then I should create a Reflection grpc-web client from https://github.com/tdex-network/reflection/blob/master/api-spec/protobuf/reflection/v1/service.proto and call `info` on it.

**Comment by Janaka-Steph** [comment]
@tiero @altafan @sekulicd We used RPC instead of grpcWeb because grpcWeb doesn't support biderectional stream https://github.com/grpc/grpc-web/blob/master/doc/streaming-roadmap.md#full-duplex-streaming-over-webtransport

```
getInfo(options?: RpcOptions): DuplexStreamingCall<GetInfoRequest, GetInfoResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetInfoRequest, GetInfoResponse>("duplex", this._transport, method, opt);
    }
```

https://github.com/timostamm/protobuf-ts/blob/3a7ce47d43113d1a80cacd0ae70630b3727eda3e/packages/grpcweb-transport/src/grpc-web-transport.ts#L81

https://github.com/tdex-network/reflection readme says `A custom version of the official [reflection](https://github.com/grpc/grpc-go/tree/master/reflection) service from grpc-go with gateway annotations making it reachable over HTTP/1.`
Maybe the bug is in that package during http1 => grpc conversion?
Please stop telling me it is on Operator interface :)

**Comment by altafan** [comment]
@Janaka-Steph closing this because it is just not a right proposal. Will open a new one.
