### ISSUE TITLE
Healt Check: After pairing error should display a modal with "Service is not available or credentials are wrong, please retry"

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-dashboard#81]

**Comment by Janaka-Steph** [comment]
We already have this non-closable modal. Is it different?

<img width="1433" alt="Screenshot 2021-11-12 at 11 28 57" src="https://user-images.githubusercontent.com/4022128/143451440-a529936e-d60b-4e4c-8673-887e91e99c51.png">

**Comment by tiero** [comment]
well, assuming the pairing was successful (ie. via proxy POST /connect) my app was then in the Home, but I got "Error 400 or 500" little down. 

Something like this, but should be sort of healt check, after pairing is succesful

**Comment by Janaka-Steph** [comment]
Ok will look at it

**Comment by Janaka-Steph** [comment]
@tiero What "retry" button should do?

**Comment by tiero** [comment]
well no retry button, just closing the moda,l we should have already the onboarding screen with the PAIR button so user can retry
