### ISSUE TITLE
Fix routing if dashboard paired with non-initialized daemon

### ISSUE THREAD

**Issue by altafan** [tdex-network/tdex-dashboard#86]
If the user pairs the dashboard with a non-initialized daemon and closes the app without completing the onboarding flow (hence leaving the daemon not initialized), he gets redirected to ONBOARDING_PAIRING the next time he'll open it.

Since the app by default attempts to [pass the connect URL down to the proxy](../tree/master/src/App.tsx#L40) in case it already exists in the store, we should add another condition in `<Routes />` in order to redirect the user to `ONBOARDING_SHOW_MNEMONIC` in case the store contains a connect URL but not a macaroon.

This way, if the user interrupts the onboarding flow, the next time he opens the app he will resume it, starting with a new seed.

**Comment by tiero** [comment]
> in order to redirect the user to ONBOARDING_SHOW_MNEMONIC

this will likely need to be redirected to a new page, required by #83  to select to wither restore or create new seed

**Comment by altafan** [comment]
I think it could be worth allowing the user to abort an onboarding flow, or he won't be able to pair with another daemon unless completing the current flow.

**Comment by tiero** [comment]
What about this?
